export const START_GET_PRODUCT = "START_GET_PRODUCT";
export const SUCCESS_GET_PRODUCT = "SUCCESS_GET_PRODUCT";
export const FAILED_GET_PRODUCT = "FAILED_GET_PRODUCT";

export const START_DELETE_PRODUCT = "START_DELETE_PRODUCT";
export const SUCCESS_DELETE_PRODUCT = "SUCCESS_DELETE_PRODUCT";
export const FAILED_DELETE_PRODUCT = "FAILED_DELETE_PRODUCT";

export const START_UPDATE_PRODUCT = "START_UPDATE_PRODUCT";
export const SUCCESS_UPDATE_PRODUCT = "SUCCESS_UPDATE_PRODUCT";
export const FAILED_UPDATE_PRODUCT = "FAILED_UPDATE_PRODUCT";

export const START_ADD_PRODUCT = "START_ADD_PRODUCT";
export const SUCCESS_ADD_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILED_ADD_PRODUCT = "FAILED_ADD_PRODUCT";